#!/usr/bin/env bash

# The upstream RPM assumes it is installed on a mutable Fedora system.  On an
# atomic image, create the groups through sysusers with stable IDs and apply
# the permissions expected by the 1Password privileged helper.

set -euo pipefail

readonly GID_ONEPASSWORD=1500
readonly GID_ONEPASSWORDCLI=1600
readonly GID_ONEPASSWORDMCP=1700
readonly BROWSER_SUPPORT_PATH=/opt/1Password/1Password-BrowserSupport
readonly MCP_PATH=/opt/1Password/onepassword-mcp

# The current RPM names the main binary `1password` (lowercase).  The old
# bling installer targeted an earlier package layout with an uppercase name.
test -x /opt/1Password/1password
test -x /usr/bin/op

chmod 4755 /opt/1Password/chrome-sandbox
chgrp "${GID_ONEPASSWORD}" "${BROWSER_SUPPORT_PATH}"
chmod g+s "${BROWSER_SUPPORT_PATH}"
chgrp "${GID_ONEPASSWORDCLI}" /usr/bin/op
chmod g+s /usr/bin/op
if [[ -x "${MCP_PATH}" ]]; then
  chgrp "${GID_ONEPASSWORDMCP}" "${MCP_PATH}"
  chmod g+s "${MCP_PATH}"
fi

cat > /usr/lib/sysusers.d/onepassword.conf <<EOF
g onepassword ${GID_ONEPASSWORD}
EOF
cat > /usr/lib/sysusers.d/onepassword-cli.conf <<EOF
g onepassword-cli ${GID_ONEPASSWORDCLI}
EOF
cat > /usr/lib/sysusers.d/onepassword-mcp.conf <<EOF
g onepassword-mcp ${GID_ONEPASSWORDMCP}
EOF

# These are generated by rpm-ostree for layered packages.  dnf installs the
# packages directly during the image build, so our fixed-ID definitions above
# are the authoritative ones.
rm -f /usr/lib/sysusers.d/30-rpmostree-pkg-group-onepassword.conf \
  /usr/lib/sysusers.d/30-rpmostree-pkg-group-onepassword-cli.conf
