---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: sixpounder-silverblue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/blue-build/base-images/fedora-silverblue-nvidia-open
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
      keys:
        - https://downloads.1password.com/linux/keys/1password.asc
    install:
      packages:
        - micro
        - starship
        - 1password
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        # - firefox
        # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
    - scope: user
      repo:
        # you can override the title to make inclusion of both system and user repos clearer
        title: Flathub (user)
    - notify: true
      scope: system
      repo:
        title: Flathub (system)
      install: # system flatpaks we want all users to have and not remove
        - com.github.tchx84.Flatseal
        - com.valvesoftware.Steam
        - io.missioncenter.MissionCenter
        - org.gnome.Loupe

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
