---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: sixpounder-silverblue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/blue-build/base-images/fedora-silverblue-nvidia-open
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      files:
        - 1password.repo
        - nordvpn.repo
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      copr:
        - atim/starship
      keys:
        - https://downloads.1password.com/linux/keys/1password.asc
        - https://repo.nordvpn.com/gpg/nordvpn_public.asc
        - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    install:
      skip-unavailable: true # skip unavailable packages
      packages:
        - repo: brave-browser
          packages:
          - brave-browser
        - micro
        - starship
        - 1password
        - nordvpn

  - type: default-flatpaks
    configurations:
      - scope: user
        install:
          - com.github.tchx84.Flatseal
          - com.valvesoftware.Steam
          - io.missioncenter.MissionCenter
          - org.gnome.Loupe

  - type: gnome-extensions
    install:
    - 3193 # Blur my Shell
    - 615 # AppIndicator and KStatusNotifierItem Support
    - 307 # Dash-to-Dock

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
        - Inter
  - type: signing
